### ISSUE TITLE
서비스 고도화 과제 정리

### ISSUE THREAD

**Issue by evan-dongmin** [dnd-side-project/dnd-6th-10-a-piece-of-writing#59]
1. 공통 정책
    - [ ] 스웨거
    - [ ] 테스트 코드
    - [ ] 포스트맨 deployment 완성
    - [ ] 페이지네이션 적용 안된 것들은 100개로 제한. (ex. 좋아요 개수, 팔로잉 개수)
    - [ ] 페이지네이션 적용되는 곳 = 게시물, 댓글
2. 신동민
    - [x] 총 반환 데이터 개수(count) - 현재 게시물 페이지네이션에 적용
    - [ ] 게시물, 댓글 예시 배포 서버 디비에 넣기
    - [ ] 댓글 - 페이지네이션 적용
    - [ ] 토픽 개수 제한.
    - [ ] 토픽의 이름 길이 제한. (12자)
3. 김태경
    - [ ] 유저별 게시글 목록 조회(파라미터를 유저 아이디로, 결과값은 게시물 목록 - 페이지네이션 적용)
    - [ ] 팔로우, 좋아요 더미 데이터 배포 디비에 더 넣기
    - [ ] 게시물 별 좋아요 표시

**Comment by SeoSang** [comment]
### 프론트

#### 게시글 관련

- [ ] InfiniteScroll 구현
- [ ] 단일 포스트 로딩
- [ ] 검색된 포스트 로딩

#### API 적용

- [ ] 좋아요 API 적용
- [ ] 팔로우 API 적용
- [ ] 댓글 API 적용

#### 기타

- [ ] 댓글 및 토픽에 길이제한

**Comment by SeoSang** [comment]
### 인프라

- [ ] 종종 서버터지는 이슈 해결
- [ ] frontend, backend 변경사항 감지해서 따로 배포
